package com.topsun.service.impl;

import com.topsun.service.ReceiveQueryTerminalParamWebService;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ReceiveQueryTerminalParamWebServiceService service = new ReceiveQueryTerminalParamWebServiceService();
 * ReceiveQueryTerminalParamWebService portType = service.getReceiveQueryTerminalParamWebServicePort();
 * portType.sendParamQueryCmd(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ReceiveQueryTerminalParamWebServiceService", targetNamespace = "http://www.tz.gps.com", wsdlLocation = "http://106.14.81.15:16666/ReceiveWorkParamQueryWebService?wsdl")
public class ReceiveQueryTerminalParamWebServiceService extends Service {

	private final static URL RECEIVEQUERYTERMINALPARAMWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(ReceiveQueryTerminalParamWebServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = ReceiveQueryTerminalParamWebServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.0.243:16666/ReceiveWorkParamQueryWebService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://106.14.81.15:16666/ReceiveWorkParamQueryWebService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RECEIVEQUERYTERMINALPARAMWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public ReceiveQueryTerminalParamWebServiceService(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ReceiveQueryTerminalParamWebServiceService() {
		super(RECEIVEQUERYTERMINALPARAMWEBSERVICESERVICE_WSDL_LOCATION,
				new QName("http://www.tz.gps.com",
						"ReceiveQueryTerminalParamWebServiceService"));
	}

	/**
	 * 
	 * @return returns ReceiveQueryTerminalParamWebService
	 */
	@WebEndpoint(name = "ReceiveQueryTerminalParamWebServicePort")
	public ReceiveQueryTerminalParamWebService getReceiveQueryTerminalParamWebServicePort() {
		return (ReceiveQueryTerminalParamWebService) super.getPort(new QName("http://www.tz.gps.com",
				"ReceiveQueryTerminalParamWebServicePort"),
				ReceiveQueryTerminalParamWebService.class);
	}

}
